### ISSUE TITLE
UI/UX Enhancement: Improve Answer Input Visibility and Accessibility

### ISSUE THREAD

**Issue by benixmaxedis** [benixmaxedis/smi-legacy#15]
## Enhancement Description
The answer input field (`#answerInput`) has several UI/UX issues that affect gameplay experience and accessibility.

## Current Issues
1. **Poor Visibility**: Input positioned at bottom-right may be hard to see during intense gameplay
2. **Small Target**: Input field may be too small for mobile/touch devices
3. **Focus Management**: Players must manually click input before typing answers
4. **Visual Feedback**: No clear indication when input is active/focused

### 1. Enhanced Positioning
```css
#answerInput {
    position: fixed; /* More reliable than absolute */
    bottom: 30px;
    right: 30px;
    z-index: 1001; /* Ensure visibility over game elements */
}
```

### 2. Better Visual Design
```css
#answerInput {
    background: rgba(0, 0, 0, 0.8);
    border: 2px solid #4a90e2;
    border-radius: 8px;
    color: #fff;
    font-size: 20px;
    padding: 12px 16px;
    min-width: 120px;
    text-align: center;
}

#answerInput:focus {
    border-color: #f39c12;
    box-shadow: 0 0 10px rgba(243, 156, 18, 0.5);
    outline: none;
}
```

### 3. Auto-Focus Improvement
- Auto-focus input when math enemies appear
- Keep focus during typing
- Clear visual indicator of focus state

### 4. Mobile Optimization
- Larger touch target (minimum 44px height)
- Better contrast for outdoor visibility
- Consider on-screen number pad for mobile

### 5. Accessibility Features
- High contrast mode support
- Screen reader labels
- Keyboard navigation support

## Implementation Priority
1. **High**: Fix positioning and visibility
2. **Medium**: Improve focus management
3. **Low**: Add mobile optimizations

## Files to Modify
- `speedy-maths-pixi.html` (CSS styles and JavaScript focus logic)

## Success Criteria
- Input field clearly visible during all gameplay phases
- Smooth typing experience without manual clicking
- Works well on mobile devices
- Meets WCAG accessibility guidelines

## Testing
- Test on multiple screen sizes
- Verify with different browsers
- Test touch interaction on mobile
- Validate with screen readers
